### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by indigodavid** [indigodavid/ezCar_backend#22]
# Kanban Board setup

## Project

[Project Link](https://github.com/indigodavid/ezCar_backend/projects/1)

## Team Members

- @ArnaudBand 
- @BregornOriginal 
- @darikmohammed 
- @indigodavid 

## Project Screenshots

![image](https://user-images.githubusercontent.com/97900045/196822396-bb92c5e5-02a3-4a5c-8238-0246989c9578.png)

![image](https://user-images.githubusercontent.com/97900045/196822451-e6678bc3-43f8-44ec-812c-d00dd4b8826f.png)

![image](https://user-images.githubusercontent.com/97900045/196822517-a43808cf-fabe-4ccb-b534-3f95b4fd79da.png)

![image](https://user-images.githubusercontent.com/97900045/196822539-7c4d9d6a-594c-48f1-9111-ba2caf71778a.png)

**Comment by Meltrust** [comment]
Hi @indigodavid,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Nice descriptions✔️ 
- All cards have points✔️ 
- Cards are fair✔️ 



Cheers and Happy coding!👏👏👏


------
